[package]
name = "monster-siren-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
uuid = { version = "1.3", features = ["v4"] }
md5 = "0.7.0"
convert_case = "0.6.0"

[lib]
proc-macro = true

[build-dependencies]
serde_json = "1.0"
