// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefSong } from "./BriefSong.js";

export type Album = { cid: string, name: string, cnNamespace: string, intro: string, belong: string, coverUrl: string, coverDeUrl: string, artistes: Array<string>, songs: Array<BriefSong>, };