// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefAlbum = { cid: string, cnNamespace: string, name: string, coverUrl: string, artistes: Array<string>, };