// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefSong = { cid: string, name: string, albumCid: string, artists: Array<string>, size: bigint | null, createTime: bigint | null, };