// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SirenBriefSongWithoutAlbumCid } from "./SirenBriefSongWithoutAlbumCid.js";

/**
 * This struct is provide for vanilla api, usually you should't use this struct
 */
export type SirenAlbumDetail = { cid: string, name: string, intro: string, belong: string, coverUrl: string, coverDeUrl: string, songs: Array<SirenBriefSongWithoutAlbumCid>, };