// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This struct is provide for vanilla api, usually you should't use this struct
 */
export type SirenBriefSongWithoutAlbumCid = { cid: string, name: string, artists: Array<string>, };