// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Song = { cid: string, name: string, albumCid: string, sourceUrl: string, lyricUrl: string | null, mvUrl: string | null, mvCoverUrl: string | null, artists: Array<string>, 
/**
 * Note: This field is not in the vanilla siren api, it only provide for application
 */
size: bigint | null, 
/**
 * Note: This field is not in the vanilla siren api, it only provide for application
 */
createTime: bigint | null, 
/**
 * Note: This field is not in the vanilla siren api, it only provide for application
 */
songCoverUrl: string | null, };